### ISSUE TITLE
使用后群晖证书无法替换

### ISSUE THREAD

**Issue by avsba001** [w0x0021/w21dsm_acme.sh#1]
大佬你好，暂不知是群晖自己bug，还是脚本触发的bug
场景为：
存在a.club 证书的情况下（默认证书），用脚本生成了a.club和b.xyz 证书，遂发现
![截图_20210411090436](https://user-images.githubusercontent.com/29015932/129033845-93da0c64-31a1-4209-9ed7-ac904210b48a.png)
证书的套用范围为空白，设置b.xyz默认证书无法替换掉现有a.club，

且已重启，已单独重启nginx，均无效

**Comment by w0x0021** [comment]
> 大佬你好，暂不知是群晖自己bug，还是脚本触发的bug 场景为：存在a.club 证书的情况下（默认证书），用脚本生成了a.club和b.xyz 证书，遂发现证书的套用范围为空白，设置b.xyz默认证书无法替换掉现有a.club...

你好，你的问题我看到了，但我暂时还没确认证书的套用范围是由哪一个配置文件控制。
        不过，在/usr/syno/etc/certificate/_archive/INFO 文件中有相关的参数，你看一下这份文件是否为空。正常来说这是一个JSON的文件，里面会包含默认证书以及证书的套用范围，但我认为套用范围不应该是这份文件控制的。好在我的脚本第45行，备份了一份/usr/syno/etc/certificate/_archive目录下的所有文件，你可以在脚本执行目录下的 backup/ 文件夹内找到原始的配置文件为了避免出错，尽量备份你的文件，按如下步骤：1、备份一份永不修改的原始文件到指定目录2、拷贝原始文件，并覆盖到 /usr/syno/etc/certificate/_archive/ 目录3、重新查看套用范围是否生效4、若生效，重新按照说明执行 w21dsm_acme.sh 最近搬家重新配置系统，正好在迁移我的主机，大概还需要一周，我才重新开启我的DSM，如果到时候还没解决可以再给我发一封邮件，我帮你看看。

**Comment by avsba001** [comment]
我查看了/usr/syno/etc/certificate/_archive/INFO，它更像它的名字一样，只是个info。但是把backup恢复到原目录的方式确实奏效了，我重新测试了一遍，又触发了这个bug，由于短时间证书申请过多，我只能暂时先放出测试办法。
        情景1.在已有a.com证书，且服务绑定至a.com的情况下，运行脚步申请a.com和b.com证书，此时a.com证书覆盖掉原证书，且服务为空白，b.com证书出现在界面
        情景2.在已有a.com证书，且服务绑定至a.com的情况下，如果此时a.com证书过期，运行脚步【同上】申请2个域名，此时a.com不会覆盖原过期证书，服务绑定在过期证书上，可以正常配置服务。
        情景3.在已有a.com证书，且服务绑定至a.com的情况下，只申请a.com证书（此时a.com未过期）,暂未测试
        情景4.在已有a.com证书，且服务绑定至a.com的情况下，只申请b.com证书，不管a.com是否过期，功能正常

**Comment by avsba001** [comment]
> font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 你好，你的问题我看到了，但我暂时还没确认证书的套用范围是由哪一个配置文件控制。 不过，在/usr/syno/etc/certificate/_archive/INFO 文件中有相关的参数，你看一下这份文件是否为空。 正常来说这是一个JSON的文件，里面会包含默认证书以及证书的套用范围，但我认为套用范围不应该是这份文件控制的。 好在我的脚本第45行，备份了一份/usr/syno/etc/certificate/_archive目录下的所有文件，你可以在脚本执行目录下的 backup/ 文件夹内找到原始的配置文件为了避免出错，尽量备份你的文件，按如下步骤：1、备份一份永不修改的原始文件到指定目录2、拷贝原始文件，并覆盖到 /usr/syno/etc/certificate/_archive/ 目录3、重新查看套用范围是否生效4、若生效，重新按照说明执行 w21dsm_acme.sh 最近搬家重新配置系统，正好在迁移我的主机，大概还需要一周，我才重新开启我的DSM，如果到时候还没解决可以再给我发一封邮件，我帮你看看。 w0x0021 ***@***.*** 在2021年8月11日 ***@***.***> 写道： 大佬你好，暂不知是群晖自己bug，还是脚本触发的bug 场景为： 存在a.club 证书的情况下（默认证书），用脚本生成了a.club和b.xyz 证书，遂发现 证书的套用范围为空白，设置b.xyz默认证书无法替换掉现有a.club， —You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.


我查看了/usr/syno/etc/certificate/_archive/INFO，它更像它的名字一样，只是个info。但是把backup恢复到原目录的方式确实奏效了，我重新测试了一遍，又触发了这个bug，由于短时间证书申请过多，我只能暂时先放出测试办法。
        情景1.在已有a.com证书，且服务绑定至a.com的情况下，运行脚步申请a.com和b.com证书，此时a.com证书覆盖掉原证书，且服务为空白，b.com证书出现在界面
        情景2.在已有a.com证书，且服务绑定至a.com的情况下，如果此时a.com证书过期，运行脚步【同上】申请2个域名，此时a.com不会覆盖原过期证书，服务绑定在过期证书上，可以正常配置服务。
        情景3.在已有a.com证书，且服务绑定至a.com的情况下，只申请a.com证书（此时a.com未过期）,暂未测试
        情景4.在已有a.com证书，且服务绑定至a.com的情况下，只申请b.com证书，不管a.com是否过期，功能正常

**Comment by avsba001** [comment]
我收回 【在已有a.com证书，且服务绑定至a.com的情况下，只申请b.com证书，不管a.com是否过期，功能正常】，已经迷糊了，168hours 不能申请证书

**Comment by w0x0021** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    你好，非常感谢你对我没有进行的测试工作进行了尝试
        按照你的描述：    "但是把backup恢复到原目录的方式确实奏效了"那我可以确认，INFO 文件具有控制套用范围的作用。
    
        根据你描述的4个情景，我大概了解到我这份脚本出错的原因了：很大可能是我没有考虑到已有证书的配置问题，因为我在申请证书之前，无法得知原有的证书目录和域名的对应关系；所以我同时也会在脚本根目录生成一份bind.json文件作为二次申请证书的记录，通过bind.json我可以找到目标域名与配置文件的路径，这样才能对应。这个地方我需要测试一下，看看如何修改，不过最近事情太忙，如果你有基于我的脚本修改完善后的代码的话，我可以邀请你参与到这个仓库中进行提交
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                w0x0021
                            
                    
                        
                            
                                    
                                    ***@***.***
                                    https://www.wangsansan.com
 

    在2021年8月12日 ***@***.***> 写道： 




font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 你好，你的问题我看到了，但我暂时还没确认证书的套用范围是由哪一个配置文件控制。 不过，在/usr/syno/etc/certificate/_archive/INFO 文件中有相关的参数，你看一下这份文件是否为空。 正常来说这是一个JSON的文件，里面会包含默认证书以及证书的套用范围，但我认为套用范围不应该是这份文件控制的。 好在我的脚本第45行，备份了一份/usr/syno/etc/certificate/_archive目录下的所有文件，你可以在脚本执行目录下的 backup/ 文件夹内找到原始的配置文件为了避免出错，尽量备份你的文件，按如下步骤：1、备份一份永不修改的原始文件到指定目录2、拷贝原始文件，并覆盖到 /usr/syno/etc/certificate/_archive/ 目录3、重新查看套用范围是否生效4、若生效，重新按照说明执行 w21dsm_acme.sh 最近搬家重新配置系统，正好在迁移我的主机，大概还需要一周，我才重新开启我的DSM，如果到时候还没解决可以再给我发一封邮件，我帮你看看。 w0x0021 @.*** 在2021年8月11日 @.***> 写道： 大佬你好，暂不知是群晖自己bug，还是脚本触发的bug 场景为： 存在a.club 证书的情况下（默认证书），用脚本生成了a.club和b.xyz 证书，遂发现 证书的套用范围为空白，设置b.xyz默认证书无法替换掉现有a.club， —You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

我查看了/usr/syno/etc/certificate/_archive/INFO，它更像它的名字一样，只是个info。但是把backup恢复到原目录的方式确实奏效了，我重新测试了一遍，又触发了这个bug，由于短时间证书申请过多，我只能暂时先放出测试办法。
情景1.在已有a.com证书，且服务绑定至a.com的情况下，运行脚步申请a.com和b.com证书，此时a.com证书覆盖掉原证书，且服务为空白，b.com证书出现在界面
情景2.在已有a.com证书，且服务绑定至a.com的情况下，如果此时a.com证书过期，运行脚步【同上】申请2个域名，此时a.com不会覆盖原过期证书，服务绑定在过期证书上，可以正常配置服务。
情景3.在已有a.com证书，且服务绑定至a.com的情况下，只申请a.com证书（此时a.com未过期）,暂未测试
情景4.在已有a.com证书，且服务绑定至a.com的情况下，只申请b.com证书，不管a.com是否过期，功能正常

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by w0x0021** [comment]
> 我查看了/usr/syno/etc/certificate/_archive/INFO，它更像它的名字一样，只是个info。但是把backup恢复到原目录的方式确实奏效了，我重新测试了一遍，又触发了这个bug，由于短时间证书申请过多，我只能暂时先放出测试办法。
情景1.在已有a.com证书，且服务绑定至a.com的情况下，运行脚步申请a.com和b.com证书，此时a.com证书覆盖掉原证书，且服务为空白，b.com证书出现在界面
情景2.在已有a.com证书，且服务绑定至a.com的情况下，如果此时a.com证书过期，运行脚步【同上】申请2个域名，此时a.com不会覆盖原过期证书，服务绑定在过期证书上，可以正常配置服务。
情景3.在已有a.com证书，且服务绑定至a.com的情况下，只申请a.com证书（此时a.com未过期）,暂未测试
情景4.在已有a.com证书，且服务绑定至a.com的情况下，只申请b.com证书，不管a.com是否过期，功能正常

你好，非常感谢你对我没有进行的测试工作进行了尝试

按照你的描述：
> "但是把backup恢复到原目录的方式确实奏效了"

那我可以确认，INFO 文件具有控制套用范围的作用。

根据你描述的4个情景，我大概了解到我这份脚本出错的原因了：
很大可能是我没有考虑到已有证书的配置问题，因为我在申请证书之前，无法得知原有的证书目录和域名的对应关系；
所以我同时也会在脚本根目录生成一份bind.json文件作为二次申请证书的记录，通过bind.json我可以找到目标域名与
配置文件的路径，这样才能对应。这个地方我需要测试一下，看看如何修改，不过最近事情太忙，可能要等两周后才有空处理。
如果你有基于我的，脚本修改完善后的代码的话，我可以邀请你参与到这个仓库中进行提交:rose:

**Comment by avsba001** [comment]
菜鸡一个，制造Bug还差不多= =，帮忙跑跑测试还行，现阶段测试7.0流程正常，暂未测试有同名未过期测试情况下的问题

**Comment by avsba001** [comment]
@w0x0021 找到另类办法解决证书替换问题，
/fullchain.cer > /usr/syno/etc/certificate/system/default/fullchain.pem
/a.cer > /usr/syno/etc/certificate/system/default/cert.pem
/a.key > /usr/syno/etc/certificate/system/default/privkey.pem

此办法可以替换证书且面板日期更新

![截图_20223109013139](https://user-images.githubusercontent.com/29015932/148670646-193e024f-c864-4b74-bccd-5ba226ae8422.png)

**Comment by w0x0021** [comment]
该bug已修复，对已造成的配置文件丢失，若未备份，可能无法完全恢复了。此处我分享一份配置，参照结构修改可尽量恢复，将以下内容替换到**/usr/syno/etc/certificate/_archive/INFO**文件内

`{
   "igSwst" : {        # 这里的igSwst替换为你新生成的证书所在的目录（在/usr/syno/etc/certificate/_archive目录下）
      "desc" : "",
      "services" : [
         {
            "display_name" : "Replication Service",
            "display_name_i18n" : "app:displayname",
            "isPkg" : true,
            "owner" : "root",
            "service" : "snapshot_receiver",
            "subscriber" : "ReplicationService"
         },
         {
            "display_name" : "MailServer-postfix",
            "display_name_i18n" : "MailServer-postfix",
            "isPkg" : true,
            "owner" : "root",
            "service" : "postfix",
            "subscriber" : "MailServer"
         },
         {
            "display_name" : "MailServer-dovecot",
            "display_name_i18n" : "MailServer-dovecot",
            "isPkg" : true,
            "owner" : "root",
            "service" : "dovecot",
            "subscriber" : "MailServer"
         },
         {
            "display_name" : "FTPS",
            "isPkg" : false,
            "owner" : "root",
            "service" : "ftpd",
            "subscriber" : "smbftpd"
         },
         {
            "display_name" : "DSM Desktop Service",
            "display_name_i18n" : "common:web_desktop",
            "isPkg" : false,
            "owner" : "root",
            "service" : "default",
            "subscriber" : "system"
         },
         {
            "display_name" : "WebDAVServer",
            "display_name_i18n" : "SYNO.SDS.WebDAVServer.Instance:app:app_name",
            "isPkg" : true,
            "owner" : "root",
            "service" : "webdav",
            "subscriber" : "WebDAVServer"
         },
         {
            "display_name" : "Synology Drive Server",
            "display_name_i18n" : "SYNO.SDS.Drive.Application:app:pkg_name",
            "isPkg" : true,
            "owner" : "SynologyDrive",
            "service" : "SynologyDrive",
            "subscriber" : "SynologyDrive"
         },
         {
            "display_name" : "Log Receiving",
            "display_name_i18n" : "helptoc:logcenter_server",
            "isPkg" : true,
            "owner" : "root",
            "service" : "pkg-LogCenter",
            "subscriber" : "LogCenter"
         }
      ]
   }
}`
