### ISSUE TITLE
可能的新bug，无法申请统配证书。

### ISSUE THREAD

**Issue by avsba001** [w0x0021/w21dsm_acme.sh#2]
之前用过Let's Encrypt 对应脚本，申请证书  "*.ex.com" "ex.com" 这种形式应该是1个统配证书，得到的证书 应该是包含  【ex.com】这个根域名的通配符证书。
实际得到  *.ex.com   ex.com   2个证书， 会导致使用*.ex.com 的时候  ex.com域名会报证书错误。

**Comment by w0x0021** [comment]
我最近也遇到这个问题，建议把通配符证书\*.ex.com放到数组最后，再尝试一次。

**Comment by avsba001** [comment]
oshit，忘了删除证书再申请，又触发之前那个bug了.....   而且。放后面的办法没用啊= =，，会不会是zerossl这个机构的问题
