### ISSUE TITLE
dsm7的nginx重加载命令变了

### ISSUE THREAD

**Issue by bsdcpp** [w0x0021/w21dsm_acme.sh#3]
感谢大佬的脚本，懒人有福了。
根据https://www.v2ex.com/t/790035讨论的末尾，群晖dsm7的重加载变成了
synow3tool --gen-all && systemctl reload nginx
麻烦核实一下，谢谢。

**Comment by w0x0021** [comment]
收到，我未安装dsm7的系统，暂未进行dsm的版本判断，建议自行修改138行
`/usr/syno/etc/rc.sysv/nginx.sh reload`
改为：
`synow3tool --gen-all && systemctl reload nginx`

另外，之前的版本存在bug，获取证书完成后，会导致配置文件丢失，控制面板中无法选择服务。尽快更新w21_acme.sh脚本，以解决该问题。已丢失的配置项，参考[丢失配置修复](https://github.com/w0x0021/w21dsm_acme.sh/issues/1#issuecomment-1136881517)手动修复一下。

**Comment by bsdcpp** [comment]
感谢大佬回复，但是按照最新的脚本，去掉了
`\"services\": []`
会导致部分配置只有一个desc，例如
```
 "16e0d5" : {
      "desc" : ""
   },
   "47ffa9" : {
      "desc" : ""
   },
   "5vWkZx" : {
      "desc" : "",
      "services" : []
   },
```
DSM证书界面就无法读取了，一片空白，无法读取配置。手动添加一行"services" : []又恢复了。

另外请教下，这个service里的就是DSM界面上显示的那些“使用范围”吧，你本次修复是怕覆盖了这些导致要每次手动设置对吧。

**Comment by bsdcpp** [comment]
大概问题我明白了，可能是因为首次执行，没有配置过，所以service本身是空的。
